import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ProgressBar from "./components/process-bar";

import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next Sanity Starter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${inter.variable} font-sans antialiased`}>
        <ProgressBar>{children}</ProgressBar>
      </body>
    </html>
  );
}
